// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

var TableNames = struct {
	Admins         string
	Blocks         string
	ChatLogs       string
	Player         string
	PlayerProgress string
	PlayerReports  string
}{
	Admins:         "admins",
	Blocks:         "blocks",
	ChatLogs:       "chat_logs",
	Player:         "player",
	PlayerProgress: "player_progress",
	PlayerReports:  "player_reports",
}
