-- +migrate Up

-- +migrate StatementBegin
ALTER TABLE `player_progress`
    MODIFY `player_id` int NOT NULL,
    MODIFY `kill_count` int unsigned NOT NULL DEFAULT '0',
    MODIFY `death_count` int unsigned NOT NULL DEFAULT '0',
    MODIFY `leader_kills` int unsigned NOT NULL DEFAULT '0',
    MODIFY `assault_kills` int unsigned NOT NULL DEFAULT '0',
    MODIFY `medic_kills` int unsigned NOT NULL DEFAULT '0',
    MODIFY `engineer_kills` int unsigned NOT NULL DEFAULT '0',
    MODIFY `support_kills` int unsigned NOT NULL DEFAULT '0',
    MODIFY `recon_kills` int unsigned NOT NULL DEFAULT '0',
    MODIFY `win_count` int unsigned NOT NULL DEFAULT '0',
    MODIFY `lose_count` int unsigned NOT NULL DEFAULT '0',
    MODIFY `friendly_shots` int unsigned NOT NULL DEFAULT '0',
    MODIFY `friendly_kills` int unsigned NOT NULL DEFAULT '0',
    MODIFY `revived` int unsigned NOT NULL DEFAULT '0',
    MODIFY `revived_team_mates` int unsigned NOT NULL DEFAULT '0',
    MODIFY `assists` int unsigned NOT NULL DEFAULT '0',
    MODIFY `prestige` int unsigned NOT NULL DEFAULT '0',
    MODIFY `current_rank` int unsigned NOT NULL DEFAULT '0',
    MODIFY `exp` int unsigned NOT NULL DEFAULT '0',
    MODIFY `shots_fired` int unsigned NOT NULL DEFAULT '0',
    MODIFY `shots_hit` int unsigned NOT NULL DEFAULT '0',
    MODIFY `headshots` int unsigned NOT NULL DEFAULT '0',
    MODIFY `completed_objectives` int unsigned NOT NULL DEFAULT '0',
    MODIFY `healed_hps` int unsigned NOT NULL DEFAULT '0',
    MODIFY `road_kills` int unsigned NOT NULL DEFAULT '0',
    MODIFY `suicides` int unsigned NOT NULL DEFAULT '0',
    MODIFY `vehicles_destroyed` int unsigned NOT NULL DEFAULT '0',
    MODIFY `vehicle_hp_repaired` int unsigned NOT NULL DEFAULT '0',
    MODIFY `longest_kill` int unsigned NOT NULL DEFAULT '0',
    MODIFY `play_time_seconds` int unsigned NOT NULL DEFAULT '0',
    MODIFY `leader_play_time` int unsigned NOT NULL DEFAULT '0',
    MODIFY `assault_play_time` int unsigned NOT NULL DEFAULT '0',
    MODIFY `medic_play_time` int unsigned NOT NULL DEFAULT '0',
    MODIFY `engineer_play_time` int unsigned NOT NULL DEFAULT '0',
    MODIFY `support_play_time` int unsigned NOT NULL DEFAULT '0',
    MODIFY `recon_play_time` int unsigned NOT NULL DEFAULT '0',
    MODIFY `leader_score` int unsigned NOT NULL DEFAULT '0',
    MODIFY `assault_score` int unsigned NOT NULL DEFAULT '0',
    MODIFY `medic_score` int unsigned NOT NULL DEFAULT '0',
    MODIFY `engineer_score` int unsigned NOT NULL DEFAULT '0',
    MODIFY `support_score` int unsigned NOT NULL DEFAULT '0',
    MODIFY `recon_score` int unsigned NOT NULL DEFAULT '0',
    MODIFY `total_score` int unsigned NOT NULL DEFAULT '0';
-- +migrate StatementEnd