# this file is used for generating the models, not for connecting to the db
# so username/password are the local dev login, not the production login
blacklist=["gorp_migrations"]
pkgname="model"
output="model"
[mysql]
  dbname="battlebit"
  host="localhost"
  port=3306
  user="battlebit"
  pass="battlebit"
  sslmode="false"